services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=NotesDB;User Id=sa;Password=NotesAPI_123!;TrustServerCertificate=True
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "NotesAPI_123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"